/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.sam.infrastructure.kafka.system.product.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum ProductCategory implements org.apache.avro.generic.GenericEnumSymbol<ProductCategory> {
  ELECTRONIC, SPORTS, HOME_APPLIANCES  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ProductCategory\",\"namespace\":\"com.sam.infrastructure.kafka.system.product.avro.model\",\"symbols\":[\"ELECTRONIC\",\"SPORTS\",\"HOME_APPLIANCES\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
