/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.sam.infrastructure.kafka.system.product.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum ProductStatus implements org.apache.avro.generic.GenericEnumSymbol<ProductStatus> {
  PENDING, AVAILABLE, PHASING_OUT, NOT_AVAILABLE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ProductStatus\",\"namespace\":\"com.sam.infrastructure.kafka.system.product.avro.model\",\"symbols\":[\"PENDING\",\"AVAILABLE\",\"PHASING_OUT\",\"NOT_AVAILABLE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
